apiVersion: v1
kind: Service
metadata:
  name: dipa-db-itzbund-@k8s.release.track@
  labels:
    app: dipa-hub
    track: @k8s.release.track@
    tenant: itzbund
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: dipa-hub
    tier: db
    tenant: itzbund
    track: @k8s.release.track@
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipa-db-itzbund-@k8s.release.track@
  labels:
    app: dipa-hub
    track: @k8s.release.track@
    tenant: itzbund
spec:
  selector:
    matchLabels:
      app: dipa-hub
      tier: db
      tenant: itzbund
      track: @k8s.release.track@
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dipa-hub
        tier: db
        tenant: itzbund
        track: @k8s.release.track@
    spec:
      containers:
        - name: dipa-db-itzbund
          image: postgres:13.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: dipa
            - name: POSTGRES_USER
              value: dipa
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
              subPath: itzbund
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: dipa-pv-claim-@k8s.release.track@
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress-mysql
#  labels:
#    app: wordpress
#spec:
#  selector:
#    matchLabels:
#      app: wordpress
#      tier: mysql
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: wordpress
#        tier: mysql
#    spec:
#      containers:
#        - image: mysql:5.6
#          name: mysql
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass
#                  key: password
#          ports:
#            - containerPort: 3306
#              name: mysql
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
#      volumes:
#        - name: mysql-persistent-storage
#          persistentVolumeClaim:
#            claimName: mysql-pv-claim

#apiVersion: v1
#kind: Service
#metadata:
#  name: dipa-db-itzbund-@k8s.release.track@
#  labels:
#    app: dipa-hub
#    track: @k8s.release.track@
#    tenant: itzbund
#spec:
#  type: NodePort
#  ports:
#    - name: dipa-db-itzbund
#    - port: 5432
#  selector:
#    app: dipa-hub
#    tier: db
#    track: @k8s.release.track@
#    tenant: itzbund
#  clusterIP: None
#---
#
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pv-claim
#  labels:
#    app: wordpress
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress-mysql
#  labels:
#    app: wordpress
#spec:
#  selector:
#    matchLabels:
#      app: wordpress
#      tier: mysql
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: wordpress
#        tier: mysql
#    spec:
#      containers:
#        - image: mysql:5.6
#          name: mysql
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass
#                  key: password
#          ports:
#            - containerPort: 3306
#              name: mysql
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
#      volumes:
#        - name: mysql-persistent-storage
#          persistentVolumeClaim:
#            claimName: mysql-pv-claim