version: '3.1'

services:

  db-weit:
    environment:
      POSTGRES_USER: 'dipa'
      POSTGRES_PASSWORD: 'dipasecret'
      POSTGRES_DB: 'dipa'
    image: postgres:13.2
    ports:
      - "5432:5432"
  db-ba:
    environment:
      POSTGRES_USER: 'dipa'
      POSTGRES_PASSWORD: 'dipasecret'
      POSTGRES_DB: 'dipa'
    image: postgres:13.2
    ports:
      - "5433:5432"
