openapi: 3.0.3
info:
  title: @project.description@
  version: @project.version@
servers:
  - url: http://localhost:9080/api/v1
    description: Development
paths:
  /adresse:
    $ref: "paths/adresse.yml"
  /status:
    $ref: "paths/status.yml"
  /timelines:
    $ref: "paths/timelines.yml"
  /timelines/projectTypes:
    $ref: "paths/projectTypes.yml"
  /timelines/projectApproaches:
    $ref: "paths/projectApproaches.yml"
  /timelines/{timelineId}:
    $ref: "paths/timeline-ops.yml"
  /timelines/{timelineId}/projectApproach:
    $ref: "paths/updateProjectApproach.yml"
  /timelines/{timelineId}/increments:
    $ref: "paths/increments.yml"
  /timelines/{timelineId}/increments/add:
    $ref: "paths/addIncrement.yml"
  /timelines/{timelineId}/increments/delete:
    $ref: "paths/deleteIncrement.yml"
  /timelines/{timelineId}/ical:
    $ref: "paths/ical.yml"
  /timelines/{timelineId}/milestones:
    $ref: "paths/milestones.yml"
  /timelines/{timelineId}/milestones/{milestoneId}:
    $ref: "paths/updateMilestone.yml"
  /timelines/{timelineId}/tasks:
    $ref: "paths/tasks.yml"
