openapi: 3.0.3
info:
  title: DiPA-OpenAPI
  version: 0.13.1
servers:
  - url: http://localhost:9080/api/v1
    description: Development
paths:
  /downloadFile/{fileId}:
    $ref: "paths/downloadFile.yml"
  /externalLinks:
    $ref: "paths/externalLinks.yml"
  /externalLinks/favorites:
    $ref: "paths/favoriteLinks.yml"
  /projectFlowSteps:
    $ref: "paths/projectFlowSteps.yml"
  /status:
    $ref: "paths/status.yml"
  /projects:
    $ref: "paths/projects.yml"
  /projects/{timelineId}/deleteProject:
    $ref: "paths/deleteProject.yml"
  /projects/{timelineId}/projectRoles:
    $ref: "paths/projectRoles.yml"
  /projects/{timelineId}/projectUsers:
    $ref: "paths/projectUsers.yml"
  /timelines:
    $ref: "paths/timelines.yml"
  /timelines/active:
    $ref: "paths/activeTimelines.yml"
  /timelines/archived:
    $ref: "paths/archivedTimelines.yml"
  /timelines/operationTypes:
    $ref: "paths/operationTypes.yml"
  /timelines/projectApproaches:
    $ref: "paths/projectApproaches.yml"
  /timelines/{timelineId}:
    $ref: "paths/updateTimeline.yml"
  /timelines/{timelineId}/project:
    $ref: "paths/projectData.yml"
  /timelines/{timelineId}/projectTasks:
    $ref: "paths/projectTasks.yml"
  /timelines/{timelineId}/permanentProjectTasks:
    $ref: "paths/permanentProjectTasks.yml"
  /timelines/{timelineId}/nonPermanentProjectTasks:
    $ref: "paths/nonPermanentProjectTasks.yml"
  /timelines/{timelineId}/projectPropertyQuestions:
    $ref: "paths/projectPropertyQuestions.yml"
  /timelines/{timelineId}/timelineTemplates:
    $ref: "paths/timelineTemplates.yml"
  /timelines/{timelineId}/timelineTemplates/{timelineTemplateId}:
    $ref: "paths/updateTimelineTemplate.yml"
  /timelines/{timelineId}/increments:
    $ref: "paths/increments.yml"
  /timelines/{timelineId}/ical:
    $ref: "paths/ical.yml"
  /timelines/{timelineId}/milestones:
    $ref: "paths/milestones.yml"
  /timelines/{timelineId}/milestones/{milestoneId}/deleteMilestone:
    $ref: "paths/deleteMilestone.yml"
  /timelines/{timelineId}/milestones/{milestoneId}/files:
    $ref: "paths/milestoneFiles.yml"
  /timelines/{timelineId}/tasks:
    $ref: "paths/tasks.yml"
  /users:
    $ref: "paths/users.yml"
  /users/currentUser:
    $ref: "paths/currentUser.yml"
