--liquibase formatted sql

-- changeset id:create-project-property-question-template-table
CREATE TABLE project_property_question_template
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name TEXT NOT NULL,
    master BOOLEAN,
    project_id BIGINT,
    CONSTRAINT "projectPropertyQuestionTemplatePK" PRIMARY KEY (id),
    CONSTRAINT "FKprojectIdPropertyQuestionTemplate" FOREIGN KEY (project_id)
        REFERENCES project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

-- changeset id:create_ProjectPropertyQuestion
CREATE TABLE project_property_question
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question TEXT NOT NULL,
    description TEXT,
    selected BOOLEAN DEFAULT true,
    sort_order INTEGER,
    project_property_question_template_id BIGINT NOT NULL,
    CONSTRAINT "projectPropertyQuestionPK" PRIMARY KEY (id),
    CONSTRAINT "FKprojectPropertyQuestionTemplate" FOREIGN KEY (project_property_question_template_id)
        REFERENCES project_property_question_template (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

-- changeset id:add-column-project-property-question-project-task
ALTER TABLE project_task
ADD project_property_question_id BIGINT,
ADD CONSTRAINT "FKprojectTaskPropertyQuestion" FOREIGN KEY (project_property_question_id)
	REFERENCES project_property_question (id) MATCH SIMPLE
	ON UPDATE NO ACTION
	ON DELETE CASCADE

-- changeset id:delete-optional-column-project-task
ALTER TABLE project_task
DROP COLUMN IF EXISTS optional

-- changeset id:create-table-permanent-project-task-template
CREATE TABLE permanent_project_task_template(
   id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
   name VARCHAR(255),
   master BOOLEAN,
   project_id BIGINT,
   CONSTRAINT "PKpermanentProjectTaskTemplate" PRIMARY KEY (id),
   CONSTRAINT "FKpermanentProjectTaskTemplateProject"
    FOREIGN KEY (project_id)
    REFERENCES project (id)
    ON DELETE CASCADE
)

-- changeset id:create-table-non-permanent-project-task-template
CREATE TABLE non_permanent_project_task_template(
   id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
   name VARCHAR(255),
   master BOOLEAN,
   project_id BIGINT,
   CONSTRAINT "PKnonPermanentProjectTaskTemplate" PRIMARY KEY (id),
   CONSTRAINT "FKnonPermanentProjectTaskTemplateProject"
    FOREIGN KEY (project_id)
    REFERENCES project (id)
    ON DELETE CASCADE
)

-- changeset id:create-table-permanent-project-task
CREATE TABLE permanent_project_task(
   id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
   title VARCHAR(255),
   icon VARCHAR(255),
   sort_order BIGINT,
   is_additional_task BOOLEAN,
   permanent_project_task_template_id BIGINT NOT NULL,
   project_task_id BIGINT,
   CONSTRAINT "PKpermanentProjectTask" PRIMARY KEY (id),
   CONSTRAINT "FKpermanentProjectTaskTemplate"
    FOREIGN KEY (permanent_project_task_template_id)
    REFERENCES permanent_project_task_template (id)
    ON DELETE CASCADE,
   CONSTRAINT "FKpermanentProjectTaskProjectTask"
    FOREIGN KEY (project_task_id)
    REFERENCES project_task (id)
    ON DELETE CASCADE
)

-- changeset id:create-table-non-permanent-project-task
CREATE TABLE non_permanent_project_task(
   id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
   title VARCHAR(255),
   icon VARCHAR(255),
   sort_order BIGINT,
   non_permanent_project_task_template_id BIGINT NOT NULL,
   project_task_id BIGINT NOT NULL,
   CONSTRAINT "PKnonPermanentProjectTask" PRIMARY KEY (id),
   CONSTRAINT "FKnonPermanentProjectTaskTemplate"
    FOREIGN KEY (non_permanent_project_task_template_id)
    REFERENCES non_permanent_project_task_template (id)
    ON DELETE CASCADE,
   CONSTRAINT "FKnonPermanentProjectTaskProjectTask"
    FOREIGN KEY (project_task_id)
    REFERENCES project_task (id)
    ON DELETE CASCADE
)

-- changeset id:add-column-task-number-project-task context:itzbund
ALTER TABLE project_task
ADD COLUMN task_number BIGINT