--liquibase formatted sql

-- changeset id:create-project-property-question-template-table
CREATE TABLE project_property_question_template
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name TEXT NOT NULL,
    master BOOLEAN,
    project_id BIGINT,
    CONSTRAINT "projectPropertyQuestionTemplatePK" PRIMARY KEY (id),
    CONSTRAINT "FKprojectIdPropertyQuestionTemplate" FOREIGN KEY (project_id)
        REFERENCES project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

-- changeset id:create_ProjectPropertyQuestion
CREATE TABLE project_property_question
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question TEXT NOT NULL,
    description TEXT,
    selected BOOLEAN DEFAULT true,
    sort_order INTEGER,
    project_property_question_template_id BIGINT NOT NULL,
    CONSTRAINT "projectPropertyQuestionPK" PRIMARY KEY (id),
    CONSTRAINT "FKprojectPropertyQuestionTemplate" FOREIGN KEY (project_property_question_template_id)
        REFERENCES project_property_question_template (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

-- changeset id:add-column-project-property-question-project-task
ALTER TABLE project_task
ADD project_property_question_id BIGINT,
ADD CONSTRAINT "FKprojectTaskPropertyQuestion" FOREIGN KEY (project_property_question_id)
	REFERENCES project_property_question (id) MATCH SIMPLE
	ON UPDATE NO ACTION
	ON DELETE CASCADE

-- changeset id:delete-optional-column-project-task
ALTER TABLE project_task
DROP COLUMN IF EXISTS optional