--liquibase formatted sql

-- changeset id:create_ProjectPropertyQuestion
CREATE TABLE project_property_question
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question TEXT NOT NULL,
    description TEXT,
    selected BOOLEAN DEFAULT true,
    sort_order INTEGER,
    project_id BIGINT NOT NULL,
    CONSTRAINT "projectPropertyQuestionPK" PRIMARY KEY (id),
    CONSTRAINT "FKprojectIdPropertyQuestion" FOREIGN KEY (project_id)
        REFERENCES public.project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

