Project:
  type: object
  properties:
    id:
      description: Unique identifier of the project
      type: integer
      format: int64
      example: 2
    name:
      description: The name of the project
      type: string
      example: "Feldberg"
    projectApproachId:
      description: Unique identifier of the linked project approach
      type: integer
      format: int64
      example: 3
  required:
    - id
    - name