Project:
  type: object
  properties:
    id:
      description: Unique identifier of the project
      type: integer
      format: int64
      example: 2
    name:
      description: The name of the project
      type: string
      example: "Feldberg"
    operationTypeId:
      description: Unique identifier of the operation type
      type: integer
      format: int64
      example: 1
    projectApproachId:
      description: Unique identifier of the project approach
      type: integer
      format: int64
      example: 2
    projectType:
      description: project type of this project
      type: string
      enum:
        - "internes Projekt"
        - "AN-Projekt"
        - null
      example: "internes Projekt"
    start:
      description: The start date of the timeline
      type: string
      format: date
      example: "2020-08-17"
    end:
      description: The end date of the timeline
      type: string
      format: date
      example: "2024-8-18"
    projectSize:
      description: size of this project
      type: string
      enum:
        - SMALL
        - MEDIUM
        - BIG
      default: null
      example: SMALL
    akz:
      description: AKZ
      type: string
      example: "01234"
    client:
      description: client
      type: string
      example: "BMF"
    department:
      description: responsible department for this project
      type: string
      example: "II A 1"
  required:
    - id
    - name
