# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check Branch or PR

on:
  push:
    branches:
      - "chore/**"
      - "feature/**"
      - "!develop"
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Install
        run: |
          npm ci
          npx ng lint dipa-frontend
          npx eslint projects/dipa-frontend/{e2e,src}/**/*.{html,js,json,jsx,ts,tsx}
        working-directory: frontend
      # - name: Set up JDK
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: "11.0.2"
      #     architecture: x64
      # - name: Build with Maven
      #   run: mvn clean install
      #   env:
      #     CI: false
