name: Release Version

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11.0.2
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'
        architecture: x64
        server-id: github
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache Frontend Build Node Modules
      uses: actions/cache@v2
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Configure Git user
      run: |
        git config user.email "actions@dipa.online"
        git config user.name "DiPA GitHub Actions"
    - name: Release with Maven
      run: mvn -B gitflow:release --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deployment to Kubernetes
      run: |
        git checkout -f main
        mkdir -p ~/.ssh
        echo -e "${{ secrets.DEPLOYMENT_SSH_KEY }}" > ~/.ssh/id_rsa
        echo -e "${{ secrets.DEPLOYMENT_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        mvn -P production-ci -B -DskipTests clean install --file pom.xml
        scp server/target/deployment/*.yaml dipa-deployment@dipa.rz-housing.tu-clausthal.de:deployment/main
        ssh dipa-deployment@dipa.rz-housing.tu-clausthal.de kubectl apply -k deployment/main
